name: polartools-dev
channels:
  - defaults
  - conda-forge
  - aps-anl-tag
  - nsls2forge
dependencies:
  - python>=3.6.0
  - scipy
  - numpy
  - pandas
  - databroker>=1.2.2
  - apstools
  - pip
  - sphinx
  - pytest
  - pytest-cov
  - databroker-pack
  - bluesky-live
  - flake8
  - lmfit
  - spec2nexus
  - versioneer
  - suitcase-csv
  - suitcase-json-metadata
  - xraylarch<=0.9.50
  - ipython
  - numpydoc
  - pyresttable
  - pip:
    - sphinx-rtd-theme
    - super-state-machine
    - sphinx-copybutton
