name: polartools-dev
channels:
  - defaults
  - conda-forge
  - aps-anl-tag
  - nsls2forge
dependencies:
  - python>=3.6.0
  - scipy
  - numpy
  - pandas
  - databroker>=1.0.6
  - pip
  - sphinx
  - pytest
  - databroker-pack
  - bluesky-live
  - flake8
  - pip:
    - ipython-genutils==0.2.0
    - prompt-toolkit==1.0.15
    - sphinx-rtd-theme
    - super-state-machine
    - versioneer
