name: polartools-dev
channels:
  - defaults
  - conda-forge
  - aps-anl-tag
  - nsls2forge
dependencies:
  - python>=3.9.0
  - scipy
  - numpy
  - pandas
  - databroker>=1.2.2
  - pip
  - sphinx
  - pytest
  - pytest-cov
  - databroker-pack
  - bluesky-live
  - flake8
  - lmfit
  - spec2nexus
  - versioneer
  - suitcase-csv
  - suitcase-json-metadata
  - suitcase-utils=0.5.3
  - ipython
  - numpydoc
  - pyresttable
  - area-detector-handlers
  - dask
  - hdf5plugin
  - apstools>=1.6.0
  - pip:
    - sphinx-rtd-theme
    - super-state-machine
    - sphinx-copybutton
